spring.datasource.url=jdbc:postgresql://localhost:5432/curriculo_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# =============================================
# Upload de Arquivos (foto do currículo)
# =============================================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
